### PR TITLE
Fix for 'Failed to eval term' for Michelson backend.

### PR DESCRIPTION
**Pull request by systemf-frank**
The error is thrown by a lack of `boundArg` for `PrimTy`, it is defaulting the `boundArg` definition in `Juvix/Core/Parameterisation.hs` which always return `Nothing`.

### NOTE THAT THIS PR SHOULD BE MERGED TO systemf-frank/polyprims

### CODE REVIEW

**Comment by systemf-frank** [comment]
With the slightly improved error messaging, we get this result:
```
$ stack run -- typecheck -b michelson nil-fail.ju
juvix: FatalError {fatalErrorMessage = "Failed to eval term: CannotApply {fun = VPrimTy List (), arg = VNeutral (NBound 0 ()) (), paramErr = NoApplyError}"}
```

**Comment by mariari** [comment]
With those traces we get an output of
```haskell
"hitting eval with"
"hitting the evalTermWith t"
"vapp"
"hit VPrimTy for s"
"for value p"
"-------------------"
List
"-------------------"
"hit vprimty"
PrimTy (Ty TInt :)
"hitting eval with"
"hitting the evalTermWith t"
"vapp"
"hit VPrimTy for s"
"for value p"
"-------------------"
List
"-------------------"
"hit vprimty"
PrimTy (Ty TInt :)
"hitting eval with"
"hitting the evalTermWith t"
"vapp"
"hit VPrimTy for s"
"for value p"
"-------------------"
List
"-------------------"
"hit here last"
"here is what t becomes"
0
"hit default"
```
before failing

**Comment by systemf-frank** [comment]
The reason `boundArg` defaults to `Nothing` for the `PrimTy` instance in the Michelson backend is simply, because there is no reason to create variables in types. While generating Michelson code we want to generate `Nil Int` vs `Nil (Bound 0)` (both in pseudo-code).

It seems we need to add a call to `substV` somewhere in the `vapp` function, similar to how it is done for lambda's:
https://github.com/anoma/juvix/blob/da8637cc829f875af47898a3c72417344c040bf1/library/Core/src/Juvix/Core/IR/Evaluator/SubstV.hs#L209

**Comment by mariari** [comment]
For now we left off at this spot in trying to propagate instances

```
    |
src/Juvix/Core/Erased/Ann/Conversion.hs:109:8-57: error: …
    • Could not deduce (Eval.HasSubstValue
                          IR.T Typed.T primTy (Types.TypedPrim primTy primVal) primTy)
        arising from a use of ‘IR.typeTerm’
      from the context: (CompConstraints primTy primVal compErr m,
                         Eval.HasPatSubstTerm
                           (OnlyExts.T Typed.T)
                           primTy
                           (Types.TypedPrim primTy primVal)
                           primTy)
        bound by the type signature for:
                   typecheckEval :: forall primTy primVal compErr (m :: * -> *).
                                    (CompConstraints primTy primVal compErr m,
                                     Eval.HasPatSubstTerm
                                       (OnlyExts.T Typed.T)
                                       primTy
                                       (Types.TypedPrim primTy primVal)
                                       primTy) =>
                                    Core.Term IR.T primTy primVal
                                    -> Usage.T
                                    -> IR.Value primTy (Types.TypedPrim primTy primVal)
                                    -> m (IR.Value primTy (Types.TypedPrim primTy primVal))
        at /home/katya/Documents/Work/repo/juvix/library/Core/src/Juvix/Core/Erased/Ann/Conversion.hs:(93,1)-(104,54)
    • In the first argument of ‘(>>=)’, namely
        ‘IR.typeTerm param term (Typed.Annotation usage ty)’
      In the first argument of ‘(|>)’, namely
        ‘IR.typeTerm param term (Typed.Annotation usage ty) >>= IR.evalTC’
      In the first argument of ‘(|>)’, namely
        ‘IR.typeTerm param term (Typed.Annotation usage ty) >>= IR.evalTC
           |> IR.execTC globals’
    |
src/Juvix/Core/Erased/Ann/Conversion.hs:155:8-57: error: …
    • Could not deduce (Eval.HasSubstValue
                          IR.T Typed.T primTy (Types.TypedPrim primTy primVal) primTy)
        arising from a use of ‘IR.typeTerm’
      from the context: (CompConstraints primTy primVal compErr m,
                         Eval.HasPatSubstTerm
                           (OnlyExts.T Typed.T)
                           primTy
                           (Types.TypedPrim primTy primVal)
                           primTy)
        bound by the type signature for:
                   typecheckErase :: forall primTy primVal compErr (m :: * -> *).
                                     (CompConstraints primTy primVal compErr m,
                                      Eval.HasPatSubstTerm
                                        (OnlyExts.T Typed.T)
                                        primTy
                                        (Types.TypedPrim primTy primVal)
                                        primTy) =>
                                     IR.Term primTy primVal
                                     -> Usage.T
                                     -> IR.Value primTy (Types.TypedPrim primTy primVal)
                                     -> m (E.Term primTy (TypedPrim primTy primVal))
        at /home/katya/Documents/Work/repo/juvix/library/Core/src/Juvix/Core/Erased/Ann/Conversion.hs:(138,1)-(149,62)
    • In the first argument of ‘(|>)’, namely
        ‘IR.typeTerm param term (Typed.Annotation usage ty)’
      In the first argument of ‘(|>)’, namely
        ‘IR.typeTerm param term (Typed.Annotation usage ty)
           |> IR.execTC globals’
      In the expression:
        IR.typeTerm param term (Typed.Annotation usage ty)
          |> IR.execTC globals
          |> fst
    |
Compilation failed.
λ> 
```

**Comment by mariari** [comment]
After commenting out the signatures in  `Conversion.hs` we are left at 

```haskell
src/Juvix/Pipeline.hs:139:21-77: error: …
    • Cannot apply expression of type ‘Core.Term IR.T primTy0 primVal0
                                       -> Juvix.Library.Usage.T
                                       -> Core.Term IR.T primTy0 primVal0
                                       -> m0
                                            (ErasedAnn.AnnTerm
                                               primTy0 (ErasedAnn.TypedPrim primTy0 primVal0))’
      to a visible type argument ‘(Err b)’
    • In the expression:
        ErasedAnn.irToErasedAnn @(Err b) inlinedTerm usage mainTy
      In an equation for ‘erasedAnn’:
          erasedAnn
            = ErasedAnn.irToErasedAnn @(Err b) inlinedTerm usage mainTy
      In the expression:
        do (usage, term, mainTy) <- getMain >>= toLambda
           let inlinedTerm = IR.inlineAllGlobals term lookupGlobal patToSym
           let erasedAnn
                 = ErasedAnn.irToErasedAnn @(Err b) inlinedTerm usage mainTy
           res <- liftIO $ fst <$> exec erasedAnn param evaluatedGlobals
           ....
    |
src/Juvix/Pipeline.hs:145:43-58: error: …
    • Could not deduce (Show compErr0)
        arising from a use of ‘pShowNoColor’
      from the context: HasBackend b
        bound by the class declaration for ‘HasBackend’
        at /home/katya/Documents/Work/repo/juvix/library/Pipeline/src/Juvix/Pipeline.hs:87:7-16
      or from: Constraints b
        bound by the type signature for:
                   toErased :: Constraints b =>
                               Core.Parameterisation (Ty b) (Val b)
                               -> Ty b
                               -> (Core.PatternMap Core.GlobalName,
                                   Core.RawGlobals IR.T (Ty b) (Val b))
                               -> Pipeline (ErasedAnn.AnnTermT (Ty b) (Val b))
        at /home/katya/Documents/Work/repo/juvix/library/Pipeline/src/Juvix/Pipeline.hs:(131,5)-(135,48)
      The type variable ‘compErr0’ is ambiguous
      Relevant bindings include
        err :: Core.PipelineError (Ty b) (Val b) compErr0
          (bound at /home/katya/Documents/Work/repo/juvix/library/Pipeline/src/Juvix/Pipeline.hs:144:12)
        res :: Either
                 (Core.PipelineError (Ty b) (Val b) compErr0)
                 (ErasedAnn.AnnTermT (Ty b) (Val b))
          (bound at /home/katya/Documents/Work/repo/juvix/library/Pipeline/src/Juvix/Pipeline.hs:140:5)
      These potential instances exist:
        instance Show A.DotNetTime
          -- Defined in ‘aeson-1.5.5.1:Data.Aeson.Types.Internal’
        instance Show A.Options
          -- Defined in ‘aeson-1.5.5.1:Data.Aeson.Types.Internal’
        instance Show a => Show (A.Result a)
          -- Defined in ‘aeson-1.5.5.1:Data.Aeson.Types.Internal’
        ...plus 245 others
        ...plus 372 instances involving out-of-scope types
        (use -fprint-potential-instances to see them all)
    • In the first argument of ‘toS’, namely ‘(pShowNoColor err)’
      In the first argument of ‘(<>)’, namely ‘toS (pShowNoColor err)’
      In the second argument of ‘(<>)’, namely
        ‘toS (pShowNoColor err) <> " on Term: " <> toS (pShowNoColor term)’
    |
Compilation failed.
```

**Comment by mariari** [comment]
I think if we add back type signautres we should be closer to working, however I'm unsure of the exact instances they should be.

**Comment by cwgoes** [comment]
What's the status here?

**Comment by mariari** [comment]
> What's the status here?

It is basically #956 we debug information

**Comment by systemf-frank** [comment]
I have added the nil-int example that should pass whenever #979 is merged onto this branch.

**Pull request merged**
