### PR TITLE
Gui for Stack-Yaml Tool

### PR DESCRIPTION
**Pull request by mariari**
This tool can visualize dependencies between our local packages

### CODE REVIEW

**Comment by Acentelles** [comment]
Really like this. Can you update the README file in yaml-generator showing how to use it?

**Review by Acentelles — APPROVED** [review]
Ack modulo README

**Comment by Acentelles** [comment]
Thanks! I think it’s a good practice to point to the references. E.g. in case of ASDF, point to https://en.wikipedia.org/wiki/Another_System_Definition_Facility, or even better: as the section in the readme is related to dependencies, point to the installation/download page

**Comment by mariari** [comment]
> Thanks! I think it’s a good practice to point to the references. E.g. in case of ASDF, point to https://en.wikipedia.org/wiki/Another_System_Definition_Facility, or even better: as the section in the readme is related to dependencies, point to the installation/download page

I can link so for ASDF and Quicklisp. Though ASDF comes with any modern CL install.

**Pull request merged**
