### PR TITLE
Add VampIR to the CI

### PR DESCRIPTION
**Pull request by jonaprieto**
This PR:

- Makes `vamp-ir` available in the CI (pre-release 0.1.2)
- [Use a setup-wasmer action to install `wasmer`](https://github.com/marketplace/actions/setup-wasmer)
- Fixes cache option value for `jaxxstorm/action-install-gh-release`'s usages

Adds support for:

- #2103 

Related: 

- https://github.com/anoma/vamp-ir/issues/90

### CODE REVIEW

**Comment by paulcadman** [comment]
We stopped using the setup-wasmer action because it was unreliable https://github.com/anoma/juvix/pull/1765 - is there any reason to change back to it now?

**Comment by jonaprieto** [comment]
> We stopped using the setup-wasmer action because it was unreliable #1765 - is there any reason to change back to it now?
> 
> I remember that https://get.wasmer.io would periodically go down, blocking the CI.

I got an error that wasmer was not found in the PATH: https://github.com/anoma/juvix/actions/runs/5023502428/jobs/9008167955#step:14:30
This was just after changing the corresponding value for `cache` from `true` to `enable`. Weird. So I remember setup-wasmer, and went to check the repo. I found it has been receiving a couple of updates lately.

**Comment by paulcadman** [comment]
> So I remember setup-wasmer, and went to check the repo. I found it has been receiving a couple of updates lately.

I'm not sure, it's still using https://get.wasmer.io/ in the action. 

Looking at the action failures, it's restored something it thinks is the wasmer binary from the cache. But something went wrong. This is perhaps a bug with the install-gh-release action?

**Comment by jonaprieto** [comment]
> > So I remember setup-wasmer, and went to check the repo. I found it has been receiving a couple of updates lately.
> 
> I'm not sure, it's still using https://get.wasmer.io/ in the action.
> 
> Looking at the action failures, it's restored something it thinks is the wasmer binary from the cache. But something went wrong. This is perhaps a bug with the install-gh-release action?
Yes, perhaps.
I suggest we merge this and possibly investigate this issue later.

**Review by paulcadman — APPROVED** [review]

**Pull request merged**
