### PR TITLE
Recurse after inlining a name

### LINKED ISSUE #806: Inlining equivalent terms only works for a single level.
```ocaml
mod LLVM where

open Prelude

open Prelude.LLVM

sig newadd : int8 -> int8 -> int8
let newadd = add int8

sig newadd2 : int8 -> int8 -> int8
let newadd2 = newadd

sig main : int8
let main = newadd 10 20
```
Note that `add` is a LLVM specific primitive.
`main` will be rewritten into `Var ("Prelude" :| ["LLVM","add"])`. When defining main in terms of `newadd2` however, it is rewritten as `Var ("LLVM" :| ["newadd"])` . Effectively there's only a single level of rewriting of equivalent terms.

According to @andy-morris this is a bug:
> that's definitely a bug
> Evaluator.inlineAllGlobalsElim should continue inlining in the Free case

### PR DESCRIPTION
**Pull request by andy-morris**
Fixes #806

Previously, the `inlineAllGlobals` function stopped after performing an inlining. Now it continues on names found inside the definition being inlined.

### CODE REVIEW

**Comment by systemf-frank** [comment]
With the fix of #805, all of the demos in examples/test/demo fail for the Michelson backend:
```
~/juvix$ stack run -- compile -b michelson test/examples/demo/const-add.ju  llvm.out && cat llvm.out
Lam' (Elim' (App' (App' (Free' (Global ("ConstAdd" :| ["make-pair"])) ()) (Elim' (Free' (Global ("ConstAdd" :| ["nil"])) ()) ()) ()) (Elim' (App' (App' (Free' (Global ("ConstAdd" :| ["add"])) ()) (Prim' (Constant (ValueInt 4)) ()) ()) (Prim' (Constant (ValueInt 6)) ()) ()) ()) ()) ()) ()
"TypecheckerError * n is of type * but VPi' Omega (VStar' 0 ()) (VStar' 0 ()) () is not *."
~/juvix$ stack run -- compile -b michelson test/examples/demo/const.ju   llvm.out && cat llvm.out
Lam' (Elim' (App' (App' (Free' (Global ("Const" :| ["make-pair"])) ()) (Elim' (Free' (Global ("Const" :| ["nil"])) ()) ()) ()) (Prim' (Constant (ValueInt 10)) ()) ()) ()) ()
"TypecheckerError * n is of type * but VPi' Omega (VStar' 0 ()) (VStar' 0 ()) () is not *."
~/juvix$ stack run -- compile -b michelson test/examples/demo/identity.ju   llvm.out && cat llvm.out
Lam' (Elim' (App' (App' (Free' (Global ("Identity" :| ["make-pair"])) ()) (Elim' (Free' (Global ("Identity" :| ["nil"])) ()) ()) ()) (Elim' (App' (Free' (Global ("Identity" :| ["car"])) ()) (Elim' (Bound' 0 ()) ()) ()) ()) ()) ()) ()
"TypecheckerError * n is of type * but VPi' Omega (VStar' 0 ()) (VStar' 0 ()) () is not *."
~/juvix$ stack run -- compile -b michelson test/examples/demo/identity_unit.ju    llvm.out && cat llvm.out
Lam' (Elim' (App' (App' (Free' (Global ("IdentityUnit" :| ["make-pair"])) ()) (Elim' (Free' (Global ("IdentityUnit" :| ["nil"])) ()) ()) ()) (Elim' (App' (Free' (Global ("IdentityUnit" :| ["car"])) ()) (Elim' (Bound' 0 ()) ()) ()) ()) ()) ()) ()
"TypecheckerError * n is of type * but VPi' Omega (VStar' 0 ()) (VStar' 0 ()) () is not *."
```

**Comment by systemf-frank** [comment]
I have verified it: the new `test/examples/positive/michelson/demo/Identity.ju` still results in an error after implementing this fix:
```
Lam' (Elim' (App' (App' (Free' (Global ("Identity" :| ["make-pair"])) ()) (Elim' (Free' (Global ("Identity" :| ["nil"])) ()) ()) ()) (Elim' (App' (Free' (Global ("Identity" :| ["car"])) ()) (Elim' (Bound' 0 ()) ()) ()) ()) ()) ()) ()
"TypecheckerError (ShouldBeStar {typeActual = VPi' Omega (VStar' 0 ()) (VStar' 0 ()) ()})"
```

Prior to this fix, it was working fine.

**Comment by systemf-frank** [comment]
The same problem as in the previous post still occurs:

```
$ stack run -- typecheck -b michelson test/examples/positive/michelson/demo/Identity.ju
"Error: TypecheckerError
    ( ShouldBeStar
        { typeActual = VPi Omega
            ( VStar 0 () )
            ( VStar 0 () ) ()
        }
    ) on Term: Lam
    ( Elim
        ( App
            ( App
                ( Free
                    ( Global
                        ( "Identity" :| [ "make-pair" ] )
                    ) ()
                )
                ( Elim
                    ( Free
                        ( Global
                            ( "Identity" :| [ "nil" ] )
                        ) ()
                    ) ()
                ) ()
            )
            ( Elim
                ( App
                    ( Free
                        ( Global
                            ( "Identity" :| [ "car" ] )
                        ) ()
                    )
                    ( Elim
                        ( Bound 0 () ) ()
                    ) ()
                ) ()
            ) ()
        ) ()
    ) ()"
```

**Comment by systemf-frank** [comment]
A more succinct example of the same problem (taken from https://github.com/anoma/juvix/issues/898):
```ocaml
mod Nil-Fail where

open Prelude
open Michelson

sig nil-int : list int
let nil-int = nil int

sig main : int -> list int
let main _ = nil-int
```

```
$ stack run -- typecheck -b michelson nil-fail.ju 
"Error: TypecheckerError
    ( ShouldBeStar
        { typeActual = VPi Omega
            ( VStar 0 () )
            ( VStar 0 () ) ()
        }
    ) on Term: Lam
    ( Elim
        ( Free
            ( Global
                ( "Nil-Fail" :| [ "nil-int" ] )
            ) ()
        ) ()
    ) ()"
```

**Review by systemf-frank — APPROVED** [review]
The changes made definitely fix the problem with inlining. The new problem that arose has a different origin and will be taken care of in separate issue #904.

Sadly this PR can not be merged yet, because it breaks the tests due to the problem mentioned in #904. That problem has to be fixed prior to merging this PR.

**Review by Acentelles — APPROVED** [review]
👍

**Review by cwgoes — APPROVED** [review]
ACK

**Pull request merged**
