### PR TITLE
Don't write log messages to stdout

### PR DESCRIPTION
**Pull request by lukaszcz**
The "Cloning (...)" message was written to stdout which messed up markdown generation.

### CODE REVIEW

**Review by janmasrovira — COMMENTED** [review]
I don't think we should suppress git messages

**Comment by paulcadman** [comment]
I think we should have logs for when things are being cloned in the normal use-case. Perhaps we could configure the output based on the current log level instead to cover use cases where you don't want them printed?

**Comment by janmasrovira** [comment]
Ideally we would redirect the git messages to the Logger effect, probably on log level info

**Comment by janmasrovira** [comment]
I mentioned the Logger effect, which prints to stderr, so that it integrates well with the existing cli flags

**Review by janmasrovira — APPROVED** [review]

**Pull request merged**
