### PR TITLE
Mariari/include semantics

### PR DESCRIPTION
**Pull request by mariari**
This PR aims to get the Context ready for Include behavior.

Includes are a rexportation of another module. Special attention is had for edge cases and incremental changes.

Thus this PR

- Implements Include logic in the context
- Implements tests 

See the tests numerous tests for examples of edge cases and behavior.

### CODE REVIEW

**Comment by paulcadman** [comment]
I think I'm misunderstanding something about module names. I tried to add a test to check that multiple includes work as expected.

So I adapted the basic tests to make two modules, "Shadows" and "London".

```
runMultiple :: IO Context.T
runMultiple = do
  created <- Context.empty (pure "Shadows")
  --
  let added1 =
        Context.addGlobal "mr-morden" (makeTm @Integer 3 |> Context.Info mempty) created
  --
  Right swap1 <-
    Context.switchNameSpace ("London" :| []) added1
  --
  let added2 =
        Context.addGlobal "new-mr-morden" (makeTm @Integer 3 |> Context.Info mempty) swap1
  --
  Right swap2 <-
    Context.switchNameSpace ("Londo" :| ["Mollari", "Centauri"]) added2

  let included1 = Context.includeMod (Context.addTopName "Shadows") swap2
  let included2 = Context.includeMod (Context.addTopName "London") included1
  --
  pure included2
```

I was expecting `mr-morden` and `new-mr-morden` to be available in the resulting context. 

```
 T.testCase
        "include multiple modules gives access to names from both modules"
        ( do
            ctx <- runMultiple
            let Just from1 = (ctx Context.!? "mr-morden")
            "TopLevel.Shadows.mr-morden" T.@=? from1 ^. Context.trueName
            traceShowM ("ctx", ctx)
            let Just from2 = (ctx Context.!? "new-mr-morden")
            "TopLevel.London.new-mr-morden" T.@=? from2 ^. Context.trueName
        ),
```

However this fails in a way I wasn't expecting. To reference`new-mr-morden` I need to lookup `London.new-mr-morden`. I guess my expectation was that `Shadows` would be the initial module in the context and the module I get by switching away from it would not include `Shadows` in its qualified name.

Have I just made a typo or have misunderstood something here?

Full context after `runMultiple`.
```
T
    { currentNameSpace = InfoRecord
        { infoRecordTable = fromList []
        , infoRecordRecord = Mod
            { moduleContents = T
                { public = fromList []
                , private = fromList []
                }
            , moduleOpenList = []
            , moduleIncludeList =
                [ "TopLevel" :| [ "London" ]
                , "TopLevel" :| [ "Shadows" ]
                ]
            , moduleQualifiedMap = map
            }
        }
    , currentName = "Londo" :|
        [ "Mollari"
        , "Centauri"
        ]
    , topLevelMap = fromList
        [
            ( "Shadows"
            , Info
                { infoTable = fromList []
                , infoDef = Module
                    ( Mod
                        { moduleContents = T
                            { public = fromList
                                [
                                    ( "mr-morden"
                                    , Info
                                        { infoTable = fromList []
                                        , infoDef = Term 3
                                        }
                                    )
                                ,
                                    ( "London"
                                    , Info
                                        { infoTable = fromList []
                                        , infoDef = Module
                                            ( Mod
                                                { moduleContents = T
                                                    { public = fromList
                                                        [
                                                            ( "new-mr-morden"
                                                            , Info
                                                                { infoTable = fromList []
                                                                , infoDef = Term 3
                                                                }
                                                            )
                                                        ]
                                                    , private = fromList []
                                                    }
                                                , moduleOpenList = []
                                                , moduleIncludeList = []
                                                , moduleQualifiedMap = map
                                                }
                                            )
                                        }
                                    )
                                ]
                            , private = fromList []
                            }
                        , moduleOpenList = []
                        , moduleIncludeList = []
                        , moduleQualifiedMap = map
                        }
                    )
                }
            )
        ,
            ( "Londo"
            , Info
                { infoTable = fromList []
                , infoDef = Module
                    ( Mod
                        { moduleContents = T
                            { public = fromList
                                [
                                    ( "Mollari"
                                    , Info
                                        { infoTable = fromList []
                                        , infoDef = Module
                                            ( Mod
                                                { moduleContents = T
                                                    { public = fromList
                                                        [
                                                            ( "Centauri"
                                                            , Info
                                                                { infoTable = fromList []
                                                                , infoDef = CurrentNameSpace
                                                                }
                                                            )
                                                        ]
                                                    , private = fromList []
                                                    }
                                                , moduleOpenList = []
                                                , moduleIncludeList = []
                                                , moduleQualifiedMap = map
                                                }
                                            )
                                        }
                                    )
                                ]
                            , private = fromList []
                            }
                        , moduleOpenList = []
                        , moduleIncludeList = []
                        , moduleQualifiedMap = map
                        }
                    )
                }
            )
        ]
    , reverseLookup = fromList []
    }
```

**Comment by mariari** [comment]
> I think I'm misunderstanding something about module names. I tried to add a test to check that multiple includes work as expected.
> 
> So I adapted the basic tests to make two modules, "Shadows" and "London".
> 
> ```
> runMultiple :: IO Context.T
> runMultiple = do
>   created <- Context.empty (pure "Shadows")
>   --
>   let added1 =
>         Context.addGlobal "mr-morden" (makeTm @Integer 3 |> Context.Info mempty) created
>   --
>   Right swap1 <-
>     Context.switchNameSpace ("London" :| []) added1
>   --
>   let added2 =
>         Context.addGlobal "new-mr-morden" (makeTm @Integer 3 |> Context.Info mempty) swap1
>   --
>   Right swap2 <-
>     Context.switchNameSpace ("Londo" :| ["Mollari", "Centauri"]) added2
> 
>   let included1 = Context.includeMod (Context.addTopName "Shadows") swap2
>   let included2 = Context.includeMod (Context.addTopName "London") included1
>   --
>   pure included2
> ```
> 
> I was expecting `mr-morden` and `new-mr-morden` to be available in the resulting context.
> 
> ```
>  T.testCase
>         "include multiple modules gives access to names from both modules"
>         ( do
>             ctx <- runMultiple
>             let Just from1 = (ctx Context.!? "mr-morden")
>             "TopLevel.Shadows.mr-morden" T.@=? from1 ^. Context.trueName
>             traceShowM ("ctx", ctx)
>             let Just from2 = (ctx Context.!? "new-mr-morden")
>             "TopLevel.London.new-mr-morden" T.@=? from2 ^. Context.trueName
>         ),
> ```
> 
> However this fails in a way I wasn't expecting. To reference`new-mr-morden` I need to lookup `London.new-mr-morden`. I guess my expectation was that `Shadows` would be the initial module in the context and the module I get by switching away from it would not include `Shadows` in its qualified name.
> 
> Have I just made a typo or have misunderstood something here?
> 
> Full context after `runMultiple`.
> 
> ```
> T
>     { currentNameSpace = InfoRecord
>         { infoRecordTable = fromList []
>         , infoRecordRecord = Mod
>             { moduleContents = T
>                 { public = fromList []
>                 , private = fromList []
>                 }
>             , moduleOpenList = []
>             , moduleIncludeList =
>                 [ "TopLevel" :| [ "London" ]
>                 , "TopLevel" :| [ "Shadows" ]
>                 ]
>             , moduleQualifiedMap = map
>             }
>         }
>     , currentName = "Londo" :|
>         [ "Mollari"
>         , "Centauri"
>         ]
>     , topLevelMap = fromList
>         [
>             ( "Shadows"
>             , Info
>                 { infoTable = fromList []
>                 , infoDef = Module
>                     ( Mod
>                         { moduleContents = T
>                             { public = fromList
>                                 [
>                                     ( "mr-morden"
>                                     , Info
>                                         { infoTable = fromList []
>                                         , infoDef = Term 3
>                                         }
>                                     )
>                                 ,
>                                     ( "London"
>                                     , Info
>                                         { infoTable = fromList []
>                                         , infoDef = Module
>                                             ( Mod
>                                                 { moduleContents = T
>                                                     { public = fromList
>                                                         [
>                                                             ( "new-mr-morden"
>                                                             , Info
>                                                                 { infoTable = fromList []
>                                                                 , infoDef = Term 3
>                                                                 }
>                                                             )
>                                                         ]
>                                                     , private = fromList []
>                                                     }
>                                                 , moduleOpenList = []
>                                                 , moduleIncludeList = []
>                                                 , moduleQualifiedMap = map
>                                                 }
>                                             )
>                                         }
>                                     )
>                                 ]
>                             , private = fromList []
>                             }
>                         , moduleOpenList = []
>                         , moduleIncludeList = []
>                         , moduleQualifiedMap = map
>                         }
>                     )
>                 }
>             )
>         ,
>             ( "Londo"
>             , Info
>                 { infoTable = fromList []
>                 , infoDef = Module
>                     ( Mod
>                         { moduleContents = T
>                             { public = fromList
>                                 [
>                                     ( "Mollari"
>                                     , Info
>                                         { infoTable = fromList []
>                                         , infoDef = Module
>                                             ( Mod
>                                                 { moduleContents = T
>                                                     { public = fromList
>                                                         [
>                                                             ( "Centauri"
>                                                             , Info
>                                                                 { infoTable = fromList []
>                                                                 , infoDef = CurrentNameSpace
>                                                                 }
>                                                             )
>                                                         ]
>                                                     , private = fromList []
>                                                     }
>                                                 , moduleOpenList = []
>                                                 , moduleIncludeList = []
>                                                 , moduleQualifiedMap = map
>                                                 }
>                                             )
>                                         }
>                                     )
>                                 ]
>                             , private = fromList []
>                             }
>                         , moduleOpenList = []
>                         , moduleIncludeList = []
>                         , moduleQualifiedMap = map
>                         }
>                     )
>                 }
>             )
>         ]
>     , reverseLookup = fromList []
>     }
> ```

After tweaking `swap1` it seems to be wroking. What happened before is that since `London` is a single word, `switchNameSpace` add it under the current module, sort of like how ocaml does

```ocaml
(* file Bar *)

module Foo = Sturct let fi = 3 ... end


(* file Baz *)

Bar.Foo.fi
```

Thus you have to say 

```haskell
  Right swap1 <-
    Context.switchNameSpace (Context.addTopName ("London" :| [])) added1
```

**Comment by paulcadman** [comment]
Thank you - this makes sense.

**Review by paulcadman — APPROVED** [review]
Jeremy took me through the code - thanks

**Pull request merged**
